apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-service-deployment
  labels:
    app: user-data-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-data-service
  template:
    metadata:
      labels:
        app: user-data-service
    spec:
      containers:
      - name: user-data-service
        image: gcr.io/linebot-reminder-431422/user_data_service:latest
        ports:
        - containerPort: 5000
